export const INPUT_TEXT_CHANGE = "INPUT_TEXT_CHANGE";
export const SET_SHIFT_HELD = "SET_SHIFT_HELD";
export const INTERPRET_REQUEST = "INTERPRET_REQUEST";
export const INTERPRET_SUCCESS = "INTERPRET_SUCCESS";
export const INTERPRET_ERROR = "INTERPRET_ERROR";
export const SET_MENU_VISIBLE = "SET_MENU_VISIBLE";
